SET FOREIGN_KEY_CHECKS=0;
DROP DATABASE IF EXISTS LIPSCOMB; 
CREATE DATABASE LIPSCOMB;
USE LIPSCOMB;

CREATE TABLE LOCATION (
    Loc_ID INT NOT NULL UNIQUE,
    Bldg_Code VARCHAR(5) NOT NULL,
    Room VARCHAR(3) NOT NULL,
    Capacity INT,
    PRIMARY KEY (Loc_ID)
)  ENGINE=INNODB DEFAULT CHARSET=UTF8MB4;

CREATE TABLE TERM (
    Term_ID INT NOT NULL UNIQUE,
    Term_Desc VARCHAR(15) NOT NULL UNIQUE,
    Status_ VARCHAR(6) NOT NULL CHECK (Status_ = 'CLOSED' OR Status_ = 'OPEN'),
    Start_Date VARCHAR(12) NOT NULL,
    PRIMARY KEY (Term_ID)
)  ENGINE=INNODB DEFAULT CHARSET=UTF8MB4;

CREATE TABLE COURSE (
    C_ID INT NOT NULL UNIQUE,
    C_No CHAR(8) NOT NULL,
    C_Name VARCHAR(50) NOT NULL,
    Credits INT DEFAULT 3,
    PRIMARY KEY (C_ID)
)  ENGINE=INNODB DEFAULT CHARSET=UTF8MB4;

CREATE TABLE FACULTY (
    F_ID INT NOT NULL UNIQUE,
    F_Last VARCHAR(20) NOT NULL,
    F_First VARCHAR(20) NOT NULL,
    F_MI CHAR(1),
    Loc_ID INT,
    F_Phone VARCHAR(15) UNIQUE,
    F_Rank VARCHAR(15),
    F_Super INT,
    F_PIN VARCHAR(5) UNIQUE,
    PRIMARY KEY (F_ID)
)  ENGINE=INNODB DEFAULT CHARSET=UTF8MB4;

CREATE TABLE STUDENT (
    S_ID INT NOT NULL UNIQUE,
    S_Last VARCHAR(20) NOT NULL,
    S_First VARCHAR(20) NOT NULL,
    S_MI CHAR(1),
    S_Address VARCHAR(30),
    S_City VARCHAR(15),
    S_State CHAR(2),
    S_Zip INT(5),
    S_Phone VARCHAR(10),
    S_Class CHAR(2),
    S_DOB VARCHAR(10) DEFAULT NULL,
    S_PIN VARCHAR(4) DEFAULT NULL UNIQUE,
    F_ID INT,
    Date_Enrolled VARCHAR(10) DEFAULT NULL,
    PRIMARY KEY (S_ID)
)  ENGINE=INNODB DEFAULT CHARSET=UTF8MB4;

CREATE TABLE COURSE_SECTION (
    C_Sec_ID INT NOT NULL UNIQUE,
    C_ID INT NOT NULL,
    Term_ID INT NOT NULL,
    Sec_Num INT DEFAULT 1,
    F_ID INT,
    Mtg_Days VARCHAR(5),
    Start_Time VARCHAR(10) ,
    End_Time VARCHAR(10) ,
    Loc_ID INT,
    Max_Enrl INT DEFAULT 30,
    PRIMARY KEY (C_Sec_ID),
    UNIQUE (Term_ID, F_ID, Mtg_Days, Start_Time)
)  ENGINE=INNODB DEFAULT CHARSET=UTF8MB4;

CREATE TABLE ENROLLMENT (
    S_ID INT NOT NULL,
    C_Sec_ID INT NOT NULL,
    Grade VARCHAR(4),
    PRIMARY KEY (S_ID , C_Sec_ID)
)  ENGINE=INNODB DEFAULT CHARSET=UTF8MB4; 

USE LIPSCOMB; 




