SET SQL_SAFE_UPDATES = 0;
UPDATE FACULTY  SET F_Super = NULL  WHERE F_Super = 0; 
UPDATE ENROLLMENT SET Grade = NULL WHERE Grade = 'NULL'; 

ALTER TABLE FACULTY  
ADD CONSTRAINT FACULTY_ibfk_1 FOREIGN KEY (Loc_ID)
	REFERENCES LOCATION (Loc_ID) 
	ON DELETE SET NULL 	
	ON UPDATE CASCADE;
ALTER TABLE FACULTY
ADD CONSTRAINT FACULTY_ibfk_2 FOREIGN KEY (F_Super)
	REFERENCES FACULTY (F_ID) 
	ON DELETE SET NULL
	ON UPDATE CASCADE; 

ALTER TABLE STUDENT
ADD CONSTRAINT STUDENT_ibfk_1 FOREIGN KEY (F_ID)
	REFERENCES FACULTY (F_ID)
	ON DELETE SET NULL 
	ON UPDATE CASCADE; 
	
ALTER TABLE COURSE_SECTION
ADD CONSTRAINT COURSE_SECTION_ibfk_1 FOREIGN KEY (C_ID)
        REFERENCES COURSE (C_ID)
        ON DELETE CASCADE ON UPDATE CASCADE,
ADD CONSTRAINT COURSE_SECTION_ibfk_2 FOREIGN KEY (Loc_ID)
        REFERENCES LOCATION (Loc_ID)
        ON DELETE SET NULL ON UPDATE CASCADE,
ADD CONSTRAINT COURSE_SECTION_ibfk_3 FOREIGN KEY (Term_ID)
        REFERENCES TERM (Term_ID)
        ON UPDATE CASCADE; 
        
ALTER TABLE ENROLLMENT
ADD CONSTRAINT ENROLLMENT_ibfk_1 FOREIGN KEY (S_ID)
        REFERENCES STUDENT (S_ID)
        ON DELETE CASCADE ON UPDATE CASCADE,
ADD CONSTRAINT ENROLLMENT_ibfk_2 FOREIGN KEY (C_Sec_ID)
        REFERENCES COURSE_SECTION (C_Sec_ID)
        ON DELETE CASCADE ON UPDATE CASCADE; 


